### ISSUE TITLE
Exiting chaincode: receive failed: rpc error: code = Unavailable desc = closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: too_many_pings

### ISSUE THREAD

**Issue by yaofeiliang** [hyperledger-labs/fabric-smart-client#311]
docker chaincode exits unexpectedly after launching samples

~~~~
# yao @ yaodeMacBook-Pro in ~/Documents/rongzer/gowork/src/github.com/hyperledger-labs/fabric-smart-client [14:35:12] 
$ docker ps -a
CONTAINER ID   IMAGE                                                                                                                                                                                         COMMAND                  CREATED          STATUS                      PORTS                                                           NAMES
1bb8b390454b   gmm3pvo26vfvtldblll224mdd4-org1peer0.org1.example.com-rbc-7eb4e0b45330eca46233d634edf4400a4132984d4cda7e99bd3962aca0c609cd-6fb8ede13c2064acfb11e87c88915e706f9c7afba0c342879ee5466da254800f   "chaincode -peer.add…"   28 minutes ago   Exited (2) 24 minutes ago                                                                   gmm3pvo26vfvtldblll224mdd4-Org1peer0.org1.example.com-rbc-7eb4e0b45330eca46233d634edf4400a4132984d4cda7e99bd3962aca0c609cd
03afd0d13665   harbor.rongzer.net/rbc/rongzer/couchdb:3                                                                                                                                                      "tini -- /docker-ent…"   31 minutes ago   Up 31 minutes               4369/tcp, 9100/tcp, 0.0.0.0:5984->5984/tcp, :::5984->5984/tcp   couchdb-sn

# yao @ yaodeMacBook-Pro in ~/Documents/rongzer/gowork/src/github.com/hyperledger-labs/fabric-smart-client [14:35:22] 
$ docker logs -f 1bb8b390454b           
Init...
Exiting chaincode: receive failed: rpc error: code = Unavailable desc = closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: too_many_pings%               

~~~~

FSC node can continue to call

Constantly calling FSC node will eventually leak memory

**Comment by adecaro** [comment]
@yaofeiliang , very interesting catch. Which FSC commit are you using?
We fixed a similar issue in the past.

**Comment by yaofeiliang** [comment]
@adecaro   Thanks for your reply, I will first pull the latest main branch code to see if it can solve my problem.

**Comment by yaofeiliang** [comment]
@adecaro  I ran the iou example of the latest branch of main, and the error still exists
~~~~

**022-07-11 15:59:45.750 CST [core.comm] ServerHandshake -> ERRO 085 Server TLS handshake failed in 133.841366ms with error EOF server=ChaincodeServer remoteaddress=10.10.10.118:61925
2022-07-11 15:59:45.912 CST [peer.chaincode.5xrpitalhnhqnlq6gck2zwjm3m-Org1_peer_0.org1.example.com-iou-8e21e98acc8091b69c5471e79777d4aefbebc31a7dc1d044fdd3f3f4e61be74f] func2 -> INFO 086 Exiting chaincode: receive failed: rpc error: code = Unavailable desc = closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: too_many_pings**
2022-07-11 15:59:45.914 CST [dockercontroller] func2 -> INFO 087 Container 5xrpitalhnhqnlq6gck2zwjm3m-Org1_peer_0.org1.example.com-iou-8e21e98acc8091b69c5471e79777d4aefbebc31a7dc1d044fdd3f3f4e61be74f has closed its IO channel

~~~~


~~~
 docker ps -a
CONTAINER ID   IMAGE                                                                                                                                                                                           COMMAND                  CREATED          STATUS          PORTS     NAMES
aaed00daaf8b   5xrpitalhnhqnlq6gck2zwjm3m-org1_peer_0.org1.example.com-iou-8e21e98acc8091b69c5471e79777d4aefbebc31a7dc1d044fdd3f3f4e61be74f-d1bff5a677f39de08aa990dc6dd387e54b077b5834c55baad4698177eff2de94   "chaincode -peer.add…"   24 seconds ago   Up 23 seconds             5xrpitalhnhqnlq6gck2zwjm3m-Org1_peer_0.org1.example.com-iou-8e21e98acc8091b69c5471e79777d4aefbebc31a7dc1d044fdd3f3f4e61be74f


$ docker logs -f aaed00daaf8b
Init...
Exiting chaincode: receive failed: rpc error: code = Unavailable desc = closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: too_many_pings%               

~~~

**Comment by adecaro** [comment]
@yaofeiliang , thanks much for your feedback. I will look at it ASAP. 
I remember that last time we had to adjust certain GRPC settings.

What is puzzling me though is that what stopped working was the chaincode but the chaincode talks to the Fabric peer not the FSC directly.
Therefore, can it be the related to the GRPC setting of the fabric peer?

**Comment by GeorgeNiotis** [comment]
any luck with that error?
I'm gettin this kind of error after running caliper benchmark tool

**Comment by mbrandenburger** [comment]
this should be cover with #1125. If issue still exists we can reopen.
